export const Ootono: Record<number, string[]> = {
  // chapter22: 天廻争乱～覇者開闢に抗いし戦鬼～
  22: [
    "uesugi",
    "mouri",
    "mogami",
    "honda",
    "sanada",
    "fukushima",
    "toyotomi",
    "toudou",
    "chosokabe",
    "kobayakawa",
    "kuroda",
    "shouneiou",
  ],
  // chapter23: 下天開闢～導かれし宿星～
  23: [
    "saito_dousan",
    "imagawa_yoshimoto",
    "akechi_mitsuhide",
    "takeda_harunobu",
    "nagao_kagetora",
    "matsudaira_motoyasu",
    "hashiba_hideyoshi",
    "matsunaga_hisahide",
    "ootomo_sourin",
    "mori_ranmaru",
    "kuki_yoshitaka",
    "araki_murashige",
    "oda_nobunaga",
  ],
  24: [
    "hachisuka",
    "hori",
    "kato",
    "kunohe",
    "kuroda",
    "maeda",
    "saika",
    "sanada",
    "shibata",
    "shimazu",
    "takenaka",
    "toyotomi",
    "ukita",
  ],
};